// <auto-generated />
using System;
using CaseItau.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseItau.Infra.Migrations
{
    [DbContext(typeof(DboContext))]
    partial class DboContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseItau.Domain.Entities.TbFeatureFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ds_Chave");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Ds_Descricao");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit")
                        .HasColumnName("Fl_Habilitado");

                    b.Property<string>("JsonConfig")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Json_Config");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("Tb_Feature_Flag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chave = "cache_redis",
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Habilita/desabilita o uso de cache Redis nas consultas de movimentações e posições.",
                            Habilitado = true,
                            JsonConfig = "{\"ExpirationInSeconds\": 60}"
                        });
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.TbFundo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("Nr_Cnpj");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Cd_Fundo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nm_Fundo");

                    b.Property<int>("TipoFundoId")
                        .HasColumnType("int")
                        .HasColumnName("Id_Tipo_Fundo");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("TipoFundoId");

                    b.ToTable("Tb_Fundo", (string)null);
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.TbMovimentacaoFundo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Movimentacao");

                    b.Property<int>("FundoId")
                        .HasColumnType("int")
                        .HasColumnName("Id_Fundo");

                    b.Property<decimal>("VlrMovimentacao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Vlr_Movimentacao");

                    b.HasKey("Id");

                    b.HasIndex("FundoId");

                    b.ToTable("Tb_Movimentacao_Fundo", (string)null);
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.TbPosicaoFundo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPosicao")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Posicao");

                    b.Property<int>("FundoId")
                        .HasColumnType("int")
                        .HasColumnName("Id_Fundo");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("Row_Version");

                    b.Property<decimal>("VlrPatrimonio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Vlr_Patrimonio");

                    b.HasKey("Id");

                    b.HasIndex("FundoId");

                    b.ToTable("Tb_Posicao_Fundo", (string)null);
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.TbTipoFundo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Nm_Tipo_Fundo");

                    b.HasKey("Id");

                    b.ToTable("Tb_Tipo_Fundo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "RENDA FIXA"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "ACOES"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "MULTI MERCADO"
                        });
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.TbFundo", b =>
                {
                    b.HasOne("CaseItau.Domain.Entities.TbTipoFundo", "TipoFundo")
                        .WithMany("Fundos")
                        .HasForeignKey("TipoFundoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoFundo");
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.TbMovimentacaoFundo", b =>
                {
                    b.HasOne("CaseItau.Domain.Entities.TbFundo", "Fundo")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("FundoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fundo");
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.TbPosicaoFundo", b =>
                {
                    b.HasOne("CaseItau.Domain.Entities.TbFundo", "Fundo")
                        .WithMany("Posicoes")
                        .HasForeignKey("FundoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fundo");
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.TbFundo", b =>
                {
                    b.Navigation("Movimentacoes");

                    b.Navigation("Posicoes");
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.TbTipoFundo", b =>
                {
                    b.Navigation("Fundos");
                });
#pragma warning restore 612, 618
        }
    }
}
